# Generated by Django 5.1.4 on 2024-12-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_created_at_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(),
        ),
    ]
